language: php
php:
    - 7.1
    - 7.2
    - 7.3
services:
    - mysql
before_install:
    - cp application/config/database.example.php application/config/database.php
    - cp application/config/secrets.example.php application/config/secrets.php
before_script:
    - sudo mysql -e 'CREATE DATABASE sharifjudge;'
env:
    matrix:
        - DRIVER="xdebug"
        - CI_VERSION="3.0-dev"
script:
    - phpunit
    - php index.php TestUnit
