language: php
php:
    - 7.2.17
services:
    - mysql
before_install:
  - cp application/config/database.example.php application/config/database.php
  - cp application/config/secrets.example.php application/config/secrets.php
  - sudo mysql -e 'CREATE DATABASE sharifjudge;'
  - composer install
env:
  matrix:
    - DRIVER="xdebug"
script:
    - php index.php TestUnit
