language: php
php:
    - 7.2
services:
    - mysql
before_script:
    - cp application/config/database.example.php application/config/database.php
    - cp application/config/secrets.example.php application/config/secrets.php
    - sudo mysql -e 'CREATE DATABASE sharifjudge;'
    - composer self-update
script:
    - php index.php TestDBInit
    - php index.php TestUnit
